# Generated by Django 3.0.8 on 2020-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0002_auto_20200812_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
