# Generated by Django 3.0.8 on 2020-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0003_recommendation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='bg_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
