# Generated by Django 3.0.8 on 2020-10-20 04:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0004_recommendation_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=128)),
                ('company_activity', models.TextField(max_length=128)),
                ('service_types', multiselectfield.db.fields.MultiSelectField(choices=[('WEB сайт', 'WEB сайт'), ('Моб. приложение', 'Моб. приложение'), ('Фото/Видео съемка', 'Фото/Видео съемка'), ('Услуги дизайна', 'Услуги дизайна'), ('Рекламная продукция', 'Рекламная продукция'), ('SMM-продвижение', 'SMM-продвижение')], max_length=128)),
            ],
        ),
    ]
